version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./frontend/static:/app/static
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
